version: '3'
services:
  postgres:
    image: postgres:13.3
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Lapka228
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'